### ISSUE TITLE
Sideeffect when using the "version" package

### ISSUE THREAD

**Issue by czaefferer** [spmvanmierlo/fastlane-plugin-flutter_bumper#1]
There is a package named ["version"](https://pub.dev/packages/version) on pub. Declaring it as a dependency in the pubspec.yaml looks like "version: ^3.0.2". This causes the versioncode-bump plugin to not only update the real version in the pubspec, but also this dependency. So:

```
version: 1.0.1+15
dependencies:
  version: ^3.0.2
```

becomes:

```
version: 1.0.1+16
dependencies:
  version: 1.0.1+16
```

**Comment by sjorsvanmierlo** [comment]
Hey, great catch! Will look into it soon!

**Comment by sjorsvanmierlo** [comment]
@czaefferer I have published a new release! Please update your Fastlane plugin to make use of the fix!
